version: '3.2'

services:
  filebeat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    environment:
     - LOGSTASH_HOST=logstash.host
     - LOGSTASH_PORT=5044
     - SHIPPER_NAME=LukeChangeName
